# Generated by Django 4.2.6 on 2023-11-04 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
                ('ratings', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='امتیاز')),
                ('slug', models.SlugField(default='', max_length=400, unique=True, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
