# Generated by Django 4.2.6 on 2023-11-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(default='', max_length=300, verbose_name='description'),
        ),
    ]
