# Generated by Django 4.2.6 on 2023-10-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('number', models.CharField(max_length=300, verbose_name='شماره')),
            ],
            options={
                'verbose_name': 'ورود',
                'verbose_name_plural': 'لیست ورود',
            },
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('fullname', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')),
                ('number', models.CharField(max_length=300, verbose_name='شماره')),
                ('age', models.IntegerField(default=0, verbose_name='سن')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'ثبت نام',
                'verbose_name_plural': 'لیست ثبت نام',
            },
        ),
    ]
