# Generated by Django 4.2.6 on 2023-10-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_login_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='register',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='fullname',
            new_name='name',
        ),
    ]
