# Generated by Django 4.2.6 on 2023-10-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_delete_login_delete_register_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
