# Generated by Django 4.2.6 on 2023-10-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={},
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='created_date',
        ),
    ]
