# Generated by Django 4.2.6 on 2023-10-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0004_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'لیست تماس با ما'},
        ),
    ]
