# Generated by Django 4.2.6 on 2023-10-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0005_alter_contactus_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='is_read_by_admin',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='response',
        ),
    ]
